import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";

const Terms = () => {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <Link to="/">
          <Button variant="ghost" className="mb-8" data-testid="button-back">
            ← Back to Home
          </Button>
        </Link>

        <h1 className="text-4xl font-bold mb-8 text-foreground">Terms and Conditions</h1>
        
        <div className="prose prose-lg dark:prose-invert max-w-none space-y-6 text-muted-foreground">
          <p className="text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Next Wife ("the Service"), you accept and agree to be bound by these Terms and Conditions. 
              The Service is provided through Telegram and allows users to interact with AI-generated virtual companions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">2. Age Requirement</h2>
            <p>
              You must be at least 18 years old to use this Service. By using Next Wife, you confirm that you are of legal age 
              in your jurisdiction. The Service contains adult content and is intended for mature audiences only.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">3. Service Description</h2>
            <p>
              Next Wife is an AI-powered virtual companion service that operates through Telegram. The Service provides:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Text-based conversations with AI companions</li>
              <li>Photo and media interactions</li>
              <li>Voice and video content</li>
              <li>Personalized relationship experiences</li>
            </ul>
            <p className="mt-4">
              All interactions are generated by artificial intelligence and do not involve real people.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">4. User Conduct</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Use the Service for any illegal purposes</li>
              <li>Attempt to reverse engineer or hack the Service</li>
              <li>Share your account credentials with others</li>
              <li>Harass, abuse, or harm other users or the Service</li>
              <li>Use the Service to generate, distribute, or request illegal content</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">5. Intellectual Property</h2>
            <p>
              All content generated by the Service, including text, images, and videos, remains the property of Next Wife. 
              Users are granted a limited, non-exclusive license to use content for personal, non-commercial purposes only.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">6. Privacy and Data</h2>
            <p>
              Your use of the Service is also governed by our Privacy Policy. We collect and process data as described in our 
              Privacy Policy to provide and improve the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">7. Disclaimer of Warranties</h2>
            <p>
              The Service is provided "as is" without warranties of any kind. Next Wife does not guarantee:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Uninterrupted or error-free service</li>
              <li>Accuracy of AI-generated content</li>
              <li>That the Service will meet your specific requirements</li>
            </ul>
            <p className="mt-4 font-semibold">
              Next Wife is an entertainment service only. AI companions are not substitutes for real human relationships, 
              therapy, or professional advice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">8. Limitation of Liability</h2>
            <p>
              Next Wife shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting 
              from your use or inability to use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">9. Subscription and Payment</h2>
            <p>
              Some features may require paid subscription. All payments are processed through Telegram's payment system. 
              Refund policies are subject to Telegram's terms of service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">10. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at any time, without notice, for 
              conduct that we believe violates these Terms or is harmful to other users or the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">11. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance 
              of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">12. Contact</h2>
            <p>
              For questions about these Terms, please contact us through our support channel: 
              <a 
                href="https://t.me/nextwifesupport" 
                target="_blank" 
                rel="noopener noreferrer"
                className="text-primary hover:underline ml-1"
              >
                @nextwifesupport
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Terms;
